                                                                                                               pg_get_functiondef                                                                                                                
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION fas_v2.analyze_pattern_detailed_weekly(p_pattern_name character varying, p_direction character varying, p_market_regime character varying, p_timeframe character varying)                                           +
  RETURNS TABLE(pattern_name character varying, timeframe character varying, direction character varying, market_regime character varying, additional_pattern character varying, total_signals bigint, winning_signals bigint, win_rate numeric)+
  LANGUAGE plpgsql                                                                                                                                                                                                                              +
 AS $function$                                                                                                                                                                                                                                  +
 BEGIN                                                                                                                                                                                                                                          +
     RETURN QUERY                                                                                                                                                                                                                               +
     WITH base_signals AS (                                                                                                                                                                                                                     +
         -- Находим базовые сигналы с нужным паттерном                                                                                                                                                                                          +
         SELECT DISTINCT                                                                                                                                                                                                                        +
             sh.id as scoring_history_id                                                                                                                                                                                                        +
         FROM fas_v2.scoring_history sh                                                                                                                                                                                                         +
         INNER JOIN fas_v2.sh_patterns shp ON sh.id = shp.scoring_history_id                                                                                                                                                                    +
         INNER JOIN fas_v2.signal_patterns sp ON shp.signal_patterns_id = sp.id                                                                                                                                                                 +
         LEFT JOIN fas_v2.sh_regime shr ON sh.id = shr.scoring_history_id                                                                                                                                                                       +
         LEFT JOIN fas_v2.market_regime mr ON shr.signal_regime_id = mr.id                                                                                                                                                                      +
         WHERE sp.pattern_type::text = p_pattern_name                                                                                                                                                                                           +
             AND sp.timeframe::text = p_timeframe                                                                                                                                                                                               +
             AND ((p_direction = 'LONG' AND sp.score_impact > 0) OR                                                                                                                                                                             +
                  (p_direction = 'SHORT' AND sp.score_impact < 0))                                                                                                                                                                              +
             AND (p_market_regime = 'ALL' OR COALESCE(mr.regime, 'UNKNOWN') = p_market_regime)                                                                                                                                                  +
             AND sh.timestamp <= CURRENT_DATE - INTERVAL '2 days'                                                                                                                                                                               +
             AND sh.timestamp >= CURRENT_DATE - INTERVAL '9 days'                                                                                                                                                                               +
     ),                                                                                                                                                                                                                                         +
     pattern_analysis AS (                                                                                                                                                                                                                      +
         -- Анализируем ВСЕ паттерны в найденных сигналах                                                                                                                                                                                       +
         SELECT                                                                                                                                                                                                                                 +
             bs.scoring_history_id,                                                                                                                                                                                                             +
             -- Проверяем наличие того же паттерна на старших ТФ                                                                                                                                                                                +
             MAX(CASE                                                                                                                                                                                                                           +
                 WHEN sp.pattern_type::text = p_pattern_name                                                                                                                                                                                    +
                     AND sp.timeframe::text != p_timeframe                                                                                                                                                                                      +
                     AND ((p_direction = 'LONG' AND sp.score_impact > 0) OR                                                                                                                                                                     +
                          (p_direction = 'SHORT' AND sp.score_impact < 0))                                                                                                                                                                      +
                 THEN sp.timeframe::text                                                                                                                                                                                                        +
             END) as higher_tf_confirmation,                                                                                                                                                                                                    +
             -- Собираем ВСЕ паттерны в правильном направлении                                                                                                                                                                                  +
             STRING_AGG(DISTINCT sp.pattern_type::text, ' + ' ORDER BY sp.pattern_type::text)                                                                                                                                                   +
                 FILTER (WHERE (p_direction = 'LONG' AND sp.score_impact > 0) OR                                                                                                                                                                +
                              (p_direction = 'SHORT' AND sp.score_impact < 0)) as all_patterns,                                                                                                                                                 +
             -- Считаем количество уникальных паттернов                                                                                                                                                                                         +
             COUNT(DISTINCT sp.pattern_type) FILTER (                                                                                                                                                                                           +
                 WHERE ((p_direction = 'LONG' AND sp.score_impact > 0) OR                                                                                                                                                                       +
                       (p_direction = 'SHORT' AND sp.score_impact < 0))                                                                                                                                                                         +
             ) as total_pattern_count                                                                                                                                                                                                           +
         FROM base_signals bs                                                                                                                                                                                                                   +
         LEFT JOIN fas_v2.sh_patterns shp ON bs.scoring_history_id = shp.scoring_history_id                                                                                                                                                     +
         LEFT JOIN fas_v2.signal_patterns sp ON shp.signal_patterns_id = sp.id                                                                                                                                                                  +
         GROUP BY bs.scoring_history_id                                                                                                                                                                                                         +
     ),                                                                                                                                                                                                                                         +
     categorized AS (                                                                                                                                                                                                                           +
         SELECT                                                                                                                                                                                                                                 +
             pa.scoring_history_id,                                                                                                                                                                                                             +
             CASE                                                                                                                                                                                                                               +
                 -- Только базовый паттерн, без других                                                                                                                                                                                          +
                 WHEN pa.all_patterns = p_pattern_name THEN 'None'                                                                                                                                                                              +
                 -- ИСПРАВЛЕНИЕ: базовый паттерн один, но есть подтверждение на другом ТФ                                                                                                                                                       +
                 WHEN pa.total_pattern_count = 1 AND pa.higher_tf_confirmation IS NOT NULL                                                                                                                                                      +
                     THEN 'Higher_TF_' || pa.higher_tf_confirmation                                                                                                                                                                             +
                 -- Конкретная комбинация паттернов                                                                                                                                                                                             +
                 ELSE pa.all_patterns                                                                                                                                                                                                           +
             END as additional                                                                                                                                                                                                                  +
         FROM pattern_analysis pa                                                                                                                                                                                                               +
     )                                                                                                                                                                                                                                          +
     -- Финальная агрегация                                                                                                                                                                                                                     +
     SELECT                                                                                                                                                                                                                                     +
         p_pattern_name::VARCHAR,                                                                                                                                                                                                               +
         p_timeframe::VARCHAR,                                                                                                                                                                                                                  +
         p_direction::VARCHAR,                                                                                                                                                                                                                  +
         p_market_regime::VARCHAR,                                                                                                                                                                                                              +
         c.additional::VARCHAR,                                                                                                                                                                                                                 +
         COUNT(*) FILTER (WHERE res.is_win IS NOT NULL)::BIGINT,                                                                                                                                                                                +
         COUNT(*) FILTER (WHERE res.is_win = true)::BIGINT,                                                                                                                                                                                     +
         ROUND(                                                                                                                                                                                                                                 +
             COUNT(*) FILTER (WHERE res.is_win = true)::numeric /                                                                                                                                                                               +
             NULLIF(COUNT(*) FILTER (WHERE res.is_win IS NOT NULL), 0) * 100,                                                                                                                                                                   +
             1                                                                                                                                                                                                                                  +
         )::NUMERIC                                                                                                                                                                                                                             +
     FROM categorized c                                                                                                                                                                                                                         +
     LEFT JOIN web.scoring_history_results_v2 res                                                                                                                                                                                               +
         ON c.scoring_history_id = res.scoring_history_id                                                                                                                                                                                       +
         AND res.signal_type = p_direction                                                                                                                                                                                                      +
     GROUP BY c.additional                                                                                                                                                                                                                      +
     HAVING COUNT(*) FILTER (WHERE res.is_win IS NOT NULL) > 0                                                                                                                                                                                  +
     ORDER BY                                                                                                                                                                                                                                   +
         CASE                                                                                                                                                                                                                                   +
             WHEN c.additional = 'None' THEN 1                                                                                                                                                                                                  +
             WHEN c.additional LIKE 'Higher_TF%' THEN 2                                                                                                                                                                                         +
             ELSE 3                                                                                                                                                                                                                             +
         END,                                                                                                                                                                                                                                   +
         COUNT(*) FILTER (WHERE res.is_win = true)::numeric /                                                                                                                                                                                   +
         NULLIF(COUNT(*) FILTER (WHERE res.is_win IS NOT NULL), 0) DESC;                                                                                                                                                                        +
 END;                                                                                                                                                                                                                                           +
 $function$                                                                                                                                                                                                                                     +
 
(1 row)

