                                                                                                   pg_get_functiondef                                                                                                    
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION fas_v2.update_scoring_history_wr(p_scoring_history_id integer, p_min_signals_weekly integer DEFAULT 5, p_min_signals_monthly integer DEFAULT 10, p_min_signals_perfect_wr integer DEFAULT 2)+
  RETURNS TABLE(best_weekly_wr numeric, best_monthly_wr numeric, weekly_pattern_match text, monthly_pattern_match text, recommended_action character varying)                                                           +
  LANGUAGE plpgsql                                                                                                                                                                                                      +
 AS $function$                                                                                                                                                                                                          +
 DECLARE                                                                                                                                                                                                                +
     v_signal_patterns TEXT[];                                                                                                                                                                                          +
     v_market_regime VARCHAR;                                                                                                                                                                                           +
     v_best_weekly_wr NUMERIC := 0;                                                                                                                                                                                     +
     v_best_monthly_wr NUMERIC := 0;                                                                                                                                                                                    +
     v_weekly_match TEXT;                                                                                                                                                                                               +
     v_monthly_match TEXT;                                                                                                                                                                                              +
     v_recommended_action VARCHAR;                                                                                                                                                                                      +
     v_has_long_patterns BOOLEAN;                                                                                                                                                                                       +
     v_has_short_patterns BOOLEAN;                                                                                                                                                                                      +
     v_signal_direction VARCHAR;                                                                                                                                                                                        +
     v_pattern_count INTEGER;                                                                                                                                                                                           +
 BEGIN                                                                                                                                                                                                                  +
     -- ===================================                                                                                                                                                                             +
     -- ВАЛИДАЦИЯ ВХОДНОГО ПАРАМЕТРА                                                                                                                                                                                    +
     -- ===================================                                                                                                                                                                             +
     IF NOT EXISTS (SELECT 1 FROM fas_v2.scoring_history WHERE id = p_scoring_history_id) THEN                                                                                                                          +
         RAISE EXCEPTION 'scoring_history_id % does not exist in fas_v2.scoring_history', p_scoring_history_id;                                                                                                         +
     END IF;                                                                                                                                                                                                            +
                                                                                                                                                                                                                        +
     -- ===================================                                                                                                                                                                             +
     -- 1. ПРОВЕРКА НАПРАВЛЕНИЙ ПАТТЕРНОВ                                                                                                                                                                               +
     -- ===================================                                                                                                                                                                             +
     SELECT                                                                                                                                                                                                             +
         bool_or(sp.score_impact > 0),                                                                                                                                                                                  +
         bool_or(sp.score_impact < 0)                                                                                                                                                                                   +
     INTO v_has_long_patterns, v_has_short_patterns                                                                                                                                                                     +
     FROM fas_v2.scoring_history sh                                                                                                                                                                                     +
     JOIN fas_v2.sh_patterns shp ON sh.id = shp.scoring_history_id                                                                                                                                                      +
     JOIN fas_v2.signal_patterns sp ON shp.signal_patterns_id = sp.id                                                                                                                                                   +
     WHERE sh.id = p_scoring_history_id;                                                                                                                                                                                +
                                                                                                                                                                                                                        +
     -- ===================================                                                                                                                                                                             +
     -- 2. ОПРЕДЕЛЕНИЕ НАПРАВЛЕНИЯ И ACTION                                                                                                                                                                             +
     -- ===================================                                                                                                                                                                             +
     IF v_has_long_patterns AND v_has_short_patterns THEN                                                                                                                                                               +
         -- Смешанный сигнал - NO_TRADE                                                                                                                                                                                 +
         v_recommended_action := 'NO_TRADE';                                                                                                                                                                            +
         UPDATE fas_v2.scoring_history                                                                                                                                                                                  +
         SET                                                                                                                                                                                                            +
             score_week = -1,                                                                                                                                                                                           +
             score_month = -1,                                                                                                                                                                                          +
             recommended_action = 'NO_TRADE'                                                                                                                                                                            +
         WHERE id = p_scoring_history_id;                                                                                                                                                                               +
                                                                                                                                                                                                                        +
         RETURN QUERY SELECT -1::NUMERIC, -1::NUMERIC,                                                                                                                                                                  +
                             'Mixed signals - NO TRADE'::TEXT,                                                                                                                                                          +
                             'Mixed signals - NO TRADE'::TEXT,                                                                                                                                                          +
                             'NO_TRADE'::VARCHAR;                                                                                                                                                                       +
         RETURN;                                                                                                                                                                                                        +
     ELSIF v_has_long_patterns THEN                                                                                                                                                                                     +
         v_recommended_action := 'BUY';                                                                                                                                                                                 +
         v_signal_direction := 'LONG';                                                                                                                                                                                  +
     ELSIF v_has_short_patterns THEN                                                                                                                                                                                    +
         v_recommended_action := 'SELL';                                                                                                                                                                                +
         v_signal_direction := 'SHORT';                                                                                                                                                                                 +
     ELSE                                                                                                                                                                                                               +
         -- Паттернов нет или они нейтральные                                                                                                                                                                           +
         v_recommended_action := 'NO_TRADE';                                                                                                                                                                            +
         UPDATE fas_v2.scoring_history                                                                                                                                                                                  +
         SET score_week = 0, score_month = 0, recommended_action = 'NO_TRADE'                                                                                                                                           +
         WHERE id = p_scoring_history_id;                                                                                                                                                                               +
                                                                                                                                                                                                                        +
         RETURN QUERY SELECT 0::NUMERIC, 0::NUMERIC,                                                                                                                                                                    +
                             'No patterns found'::TEXT,                                                                                                                                                                 +
                             'No patterns found'::TEXT,                                                                                                                                                                 +
                             'NO_TRADE'::VARCHAR;                                                                                                                                                                       +
         RETURN;                                                                                                                                                                                                        +
     END IF;                                                                                                                                                                                                            +
                                                                                                                                                                                                                        +
     -- ===================================                                                                                                                                                                             +
     -- 3. ПОЛУЧЕНИЕ ПАТТЕРНОВ И РЕЖИМА РЫНКА                                                                                                                                                                           +
     -- ===================================                                                                                                                                                                             +
     SELECT                                                                                                                                                                                                             +
         array_agg(DISTINCT sp.pattern_type::text ORDER BY sp.pattern_type::text),                                                                                                                                      +
         COALESCE(mr.regime, 'UNKNOWN')                                                                                                                                                                                 +
     INTO v_signal_patterns, v_market_regime                                                                                                                                                                            +
     FROM fas_v2.scoring_history sh                                                                                                                                                                                     +
     JOIN fas_v2.sh_patterns shp ON sh.id = shp.scoring_history_id                                                                                                                                                      +
     JOIN fas_v2.signal_patterns sp ON shp.signal_patterns_id = sp.id                                                                                                                                                   +
     LEFT JOIN fas_v2.sh_regime shr ON sh.id = shr.scoring_history_id                                                                                                                                                   +
     LEFT JOIN fas_v2.market_regime mr ON shr.signal_regime_id = mr.id                                                                                                                                                  +
     WHERE sh.id = p_scoring_history_id                                                                                                                                                                                 +
       AND ((v_signal_direction = 'LONG' AND sp.score_impact > 0) OR                                                                                                                                                    +
            (v_signal_direction = 'SHORT' AND sp.score_impact < 0))                                                                                                                                                     +
     GROUP BY mr.regime;                                                                                                                                                                                                +
                                                                                                                                                                                                                        +
     -- Сохраняем количество паттернов для проверки штрафа                                                                                                                                                              +
     v_pattern_count := array_length(v_signal_patterns, 1);                                                                                                                                                             +
                                                                                                                                                                                                                        +
     -- ===================================                                                                                                                                                                             +
     -- 4. ПОИСК ТОЧНОГО СООТВЕТСТВИЯ В WEEKLY                                                                                                                                                                          +
     -- ===================================                                                                                                                                                                             +
     SELECT                                                                                                                                                                                                             +
         paw.win_rate,                                                                                                                                                                                                  +
         paw.pattern_name || ' on ' || paw.timeframe                                                                                                                                                                    +
     INTO v_best_weekly_wr, v_weekly_match                                                                                                                                                                              +
     FROM web.pattern_analysis_weekly paw                                                                                                                                                                               +
     WHERE                                                                                                                                                                                                              +
         paw.pattern_list @> v_signal_patterns                                                                                                                                                                          +
         AND paw.pattern_list <@ v_signal_patterns                                                                                                                                                                      +
         AND paw.market_regime = v_market_regime                                                                                                                                                                        +
         AND paw.direction = v_signal_direction                                                                                                                                                                         +
         AND (paw.total_signals >= p_min_signals_weekly OR                                                                                                                                                              +
              (paw.total_signals >= p_min_signals_perfect_wr AND paw.win_rate = 100))                                                                                                                                   +
     ORDER BY paw.win_rate DESC, paw.total_signals DESC                                                                                                                                                                 +
     LIMIT 1;                                                                                                                                                                                                           +
                                                                                                                                                                                                                        +
     -- ===================================                                                                                                                                                                             +
     -- 5. ПОИСК ТОЧНОГО СООТВЕТСТВИЯ В MONTHLY                                                                                                                                                                         +
     -- ===================================                                                                                                                                                                             +
     SELECT                                                                                                                                                                                                             +
         pam.win_rate,                                                                                                                                                                                                  +
         pam.pattern_name || ' on ' || pam.timeframe                                                                                                                                                                    +
     INTO v_best_monthly_wr, v_monthly_match                                                                                                                                                                            +
     FROM web.pattern_analysis_monthly pam                                                                                                                                                                              +
     WHERE                                                                                                                                                                                                              +
         pam.pattern_list @> v_signal_patterns                                                                                                                                                                          +
         AND pam.pattern_list <@ v_signal_patterns                                                                                                                                                                      +
         AND pam.market_regime = v_market_regime                                                                                                                                                                        +
         AND pam.direction = v_signal_direction                                                                                                                                                                         +
         AND (pam.total_signals >= p_min_signals_monthly OR                                                                                                                                                             +
              (pam.total_signals >= p_min_signals_perfect_wr+1 AND pam.win_rate = 100))                                                                                                                                 +
     ORDER BY pam.win_rate DESC, pam.total_signals DESC                                                                                                                                                                 +
     LIMIT 1;                                                                                                                                                                                                           +
                                                                                                                                                                                                                        +
     -- ===================================                                                                                                                                                                             +
     -- 6. ОБРАБОТКА РЕЗУЛЬТАТОВ                                                                                                                                                                                        +
     -- ===================================                                                                                                                                                                             +
     v_best_weekly_wr := COALESCE(v_best_weekly_wr, 0);                                                                                                                                                                 +
     v_best_monthly_wr := COALESCE(v_best_monthly_wr, 0);                                                                                                                                                               +
     v_weekly_match := COALESCE(v_weekly_match, 'No exact match found');                                                                                                                                                +
     v_monthly_match := COALESCE(v_monthly_match, 'No exact match found');                                                                                                                                              +
                                                                                                                                                                                                                        +
     -- ===================================                                                                                                                                                                             +
     -- 7. ШТРАФ ЗА ПРОТИВОТРЕНДОВЫЕ СИГНАЛЫ                                                                                                                                                                            +
     -- ===================================                                                                                                                                                                             +
     -- Если LONG на BEAR или SHORT на BULL, и только 1 паттерн - штраф -30                                                                                                                                             +
     IF (                                                                                                                                                                                                               +
         (v_signal_direction = 'LONG' AND v_market_regime = 'BEAR') OR                                                                                                                                                  +
         (v_signal_direction = 'SHORT' AND v_market_regime = 'BULL')                                                                                                                                                    +
     ) AND v_pattern_count = 1 THEN                                                                                                                                                                                     +
         -- Применяем штраф, но не уходим в отрицательные значения                                                                                                                                                      +
         IF v_best_weekly_wr > 0 THEN                                                                                                                                                                                   +
             v_best_weekly_wr := GREATEST(0, v_best_weekly_wr - 30);                                                                                                                                                    +
             v_weekly_match := v_weekly_match || ' (penalty -30: counter-trend single pattern)';                                                                                                                        +
         END IF;                                                                                                                                                                                                        +
                                                                                                                                                                                                                        +
         IF v_best_monthly_wr > 0 THEN                                                                                                                                                                                  +
             v_best_monthly_wr := GREATEST(0, v_best_monthly_wr - 30);                                                                                                                                                  +
             v_monthly_match := v_monthly_match || ' (penalty -30: counter-trend single pattern)';                                                                                                                      +
         END IF;                                                                                                                                                                                                        +
     END IF;                                                                                                                                                                                                            +
                                                                                                                                                                                                                        +
     -- ===================================                                                                                                                                                                             +
     -- 8. ОБНОВЛЕНИЕ SCORING_HISTORY                                                                                                                                                                                   +
     -- ===================================                                                                                                                                                                             +
     UPDATE fas_v2.scoring_history                                                                                                                                                                                      +
     SET                                                                                                                                                                                                                +
         score_week = v_best_weekly_wr,                                                                                                                                                                                 +
         score_month = v_best_monthly_wr,                                                                                                                                                                               +
         recommended_action = v_recommended_action                                                                                                                                                                      +
     WHERE id = p_scoring_history_id;                                                                                                                                                                                   +
                                                                                                                                                                                                                        +
     -- ===================================                                                                                                                                                                             +
     -- 9. ВОЗВРАТ РЕЗУЛЬТАТОВ                                                                                                                                                                                          +
     -- ===================================                                                                                                                                                                             +
     RETURN QUERY                                                                                                                                                                                                       +
     SELECT                                                                                                                                                                                                             +
         v_best_weekly_wr,                                                                                                                                                                                              +
         v_best_monthly_wr,                                                                                                                                                                                             +
         v_weekly_match,                                                                                                                                                                                                +
         v_monthly_match,                                                                                                                                                                                               +
         v_recommended_action;                                                                                                                                                                                          +
 END;                                                                                                                                                                                                                   +
 $function$                                                                                                                                                                                                             +
 
(1 row)

